[phases.setup]
    nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.install]
    cmds = ["composer install --no-dev --no-interaction --prefer-dist --ignore-platform-reqs --no-scripts"]

[phases.build]
    cmds = ["npm ci", "npm run build"]

[start]
    cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
